ITSR-106 ITSR-107 ITSR-108 ITSR-109 ITSR-120
IT-S-BMSTU/Registration-Bot pull request #34
Opened 2023-11-29 11:47 UTC by zhikh23

2023-12-02 15:48 UTC, darleet commented
В следующий раз добавляй меня в reviewers, чтобы меня пинговало

2023-12-02 16:46 UTC, darleet commented
Интересное название PR-а))
По крайней мере названия нужно писать для красивой истории, чтобы понять, где что-то пошло не так

2023-12-03 00:04 UTC, darleet requested changes
Все замечания отписал в комментах, в целом все неплохо

2023-12-03 13:38 UTC, zhikh23 commented on api_gateway/cmd/server/server.go
![image](https://github.com/IT-S-BMSTU/Registration-Bot/assets/130099896/8fe2b907-e527-4bfc-98e5-1a1f0be254a9)
Пример REST-сервера на Go, от которого я многое взял. 
Но здесь окей, можно переместить в `internal`

2023-12-03 13:49 UTC, zhikh23 commented on api_gateway/internal/api/api.databaseservice.go
3. https://github.com/snykk/go-rest-boilerplate/tree/master

2023-12-03 14:28 UTC, zhikh23 commented on api_gateway/internal/api/api.databaseservice.go
> I'd appreciate having it as a documented standard
Пока это не стандарт. Но окей, переименую

2023-12-03 14:34 UTC, darleet commented on api_gateway/internal/api/api.databaseservice.go
Ты можешь назвать файлы короче, это самый оптимальный вариант, а также существует вариант называть файлы просто слитно в одно слово. CamelCase я не приветствую, потому что он иногда используется для моков отдельных структур

Стандарт формируется ответственными участниками сообщества, мы сами в ответе за тех, кого приручили)

2023-12-03 18:00 UTC, Encapsulateed commented
> Интересное название PR-а)) Названия нужно писать для красивой истории: так можно понять, где что-то пошло не так

Согласен, в пуле надо описывать то чем ты занимался.

2024-03-09 18:52 UTC, darleet commented
outdated

2024-03-09 18:52 UTC, closed without merging