Реализация полного функционала Бота-Опросника
IT-S-BMSTU/Registration-Bot pull request #5
Opened 2023-04-12 22:48 UTC by darleet

### Краткие сведения

- Был реализован механизм FSM для сохранения промежуточных ответов пользователя на вопросы. Для FSM используется Redis, который позволяет хранить данные не в ОЗУ, а в долговременной памяти.
- Добавлена поддержка инлайновых кнопок.
- Реализован весь необходимый функционал для ветвления анкет.
- Изменена структура БД.
- БД изменена на PostgreSQL.

### Изменение структуры БД

Теперь для каждого бота-опросника создается своя база данных. В каждой базе данных присутствует три таблицы: `answers`, `questions`, `buttons`. 

- `answers` отвечает за сохранение ответов пользователей.
- `questions` хранит вопросы анкеты.
- `buttons` хранит связь между кнопками и вопросами.

2023-04-13 15:22 UTC, Encapsulateed requested changes
В комментах написано, чё изменить. Основная претензия к отсутствию многопоточности. 
Асинхронность != Параллельность

2023-04-13 15:22 UTC, Encapsulateed commented on asker_bot/bot_instance.py
> +async def run_instance(token, bot_id):
async def run_instance(token, bot_id):
Важно, что это функция не только асинхронная. Она должна запускаться в отдельном потоке.

2023-04-20 19:20 UTC, darleet commented on tests/main.py
> +    await bot_instance.run_instance(config.bot_token, 1)
Многопоточность подразумевается самим поллингом. Resolved

2023-04-20 19:21 UTC, darleet commented on .gitignore
> +config.py
Гитигнор для всех подпроектов использую общий, не хочу dry нарушать

2023-04-21 10:21 UTC, Encapsulateed approved these changes
Во, теперь база

2023-04-21 10:21 UTC, Encapsulateed commented on asker_bot/bot_instance.py
> +
На будущее )
Если уже ты прописал try except блок для SQL кода. В случае ошибки нужно закрывать подключение.

2023-04-21 10:21 UTC, merged